baseURL = "http://rafmrs.com/"
languageCode = "en-gb"
paginate = 10
theme = "blank"
title = "Rafael Morais"
[markup.highlight]
codeFences = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "solarized-light"
tabWidth = 4
[[menu.main]]
identifier = "linked-in"
name = "LinkedIn"
url = "https://www.linkedin.com/in/rafmrs"
weight = 5
[[menu.main]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/rafmst"
weight = 4
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/rafmst"
weight = 3
[params]
AuthorName = "Rafael Morais"
Description = "Most of the time backend developer, and occasionally a creative."
ShowDatesOnPosts = true
